Repository GemWallet/gemwallet-extension, pull requests merged in 2023-03, with the labels that each got.

#112 Feat/expose types to API
  packages/api/releaseNpm.js
  packages/api/src/index.ts
Labels: enhancement

#113 Transaction details improvement
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.mock.ts
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.test.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/index.css
  packages/extension/src/types/transaction.types.ts
Labels: enhancement

#116 Bump GemWallet API to 2.2.1
  dist/gemwallet-api.js
  packages/api/package.json
Labels: dependencies

#117 Bugfix/send reponse extension closed
  packages/api/src/helpers/extensionMessaging.ts
  packages/extension/package.json
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/hooks/index.ts
  packages/extension/src/hooks/useBeforeUnload/index.ts
  packages/extension/src/hooks/useBeforeUnload/useBeforeUnload.test.tsx
  packages/extension/src/hooks/useBeforeUnload/useBeforeUnload.tsx
  packages/extension/src/react-app-env.d.ts
  yarn.lock
Labels: bugfix

#118 Fix issue with extension opening more than one time
  dist/gemwallet-api.js
  packages/api/src/addTrustline/addTrustline.ts
  packages/api/src/getAddress/getAddress.ts
  packages/api/src/getNFT/getNFT.ts
  packages/api/src/getNetwork/getNetwork.test.ts
  packages/api/src/getNetwork/getNetwork.ts
  packages/api/src/getPublicKey/getPublicKey.ts
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/isConnected/isConnected.ts
  packages/api/src/sendPayment/sendPayment.ts
  packages/api/src/signMessage/signMessage.ts
  packages/constants/src/event/event.types.ts
  packages/constants/src/index.ts
  packages/constants/src/message/message.constant.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/public/manifest.json
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/ShareAddress/ShareAddress.tsx
  packages/extension/src/components/pages/ShareNFT/ShareNFT.tsx
  packages/extension/src/components/pages/SharePublicKey/SharePublicKey.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
Labels: bugfix
