Repository GemWallet/gemwallet-extension, pull requests merged in 2023-04, with the labels that each got.

#122 Fix issue with extension opening more than once
  dist/gemwallet-api.js
  packages/constants/src/payload/payload.types.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/contexts/BrowserContext/BrowserContext.tsx
Labels: bugfix

#123 Release 2.6.0
  dist/gemwallet-api.js
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/package.json
  packages/extension/public/manifest.json
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  yarn.lock
Labels: dependencies

#124 Send Payment retrocompatible
  dist/gemwallet-api.js
  packages/api/src/sendPayment/sendPayment.ts
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
Labels: dependencies

#126 Feat/send
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/package.json
  packages/extension/src/App.tsx
  packages/extension/src/components/atoms/NumericInput/NumericInput.test.tsx
  packages/extension/src/components/atoms/NumericInput/NumericInput.tsx
  packages/extension/src/components/atoms/NumericInput/index.ts
  packages/extension/src/components/atoms/index.ts
  packages/extension/src/components/organisms/Header/Header.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/index.ts
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/index.ts
  packages/extension/src/components/pages/SendPayment/SendPayment.tsx
  packages/extension/src/components/pages/SendPayment/index.ts
  packages/extension/src/components/pages/index.ts
  packages/extension/src/components/templates/AsyncTransaction/AsyncTransaction.tsx
  packages/extension/src/components/templates/ErrorBoundary/ErrorBoundary.tsx
  packages/extension/src/components/templates/PageWithHeader/PageWithHeader.tsx
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/utils/truncateAddress.test.ts
  packages/extension/src/utils/truncateAddress.ts
  yarn.lock
Labels: enhancement, E2E

#127 Update GemWallet README
  README.md
Labels: documentation

#131 Fix HEX issue within the send payment option
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
Labels: bugfix

#132 Bump package to 2.7.1
  packages/extension/package.json
  packages/extension/public/manifest.json
Labels: dependencies

#133 Add CI: Integration
  .github/workflows/integration.yml
  package.json
  packages/extension/cypress/e2e/networks.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/cypress/e2e/wallet_management.cy.ts
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.test.tsx
Labels: enhancement

#136 Update README: Add some shields.io links
  README.md
Labels: documentation

#142 Autofocus password
  packages/extension/src/components/pages/Login/Login.tsx
Labels: enhancement

#144 Handle transaction memos
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/SendPayment/SendPayment.tsx
  packages/extension/src/constants/payload.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/payment.test.ts
  packages/extension/src/utils/payment.ts
Labels: enhancement

#146 Fix the send payment when there are no funds
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
Labels: bugfix

#145 Handle transaction destination tags
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/SendPayment/SendPayment.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/utils/payment.test.ts
  packages/extension/src/utils/payment.ts
Labels: enhancement

#147 Release 2.8.0
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#148 Check transactions history with Cypress
  packages/extension/cypress/e2e/send_token.cy.ts
Labels: E2E
