Repository GemWallet/gemwallet-extension, pull requests merged in 2023-08, with the labels that each got.

#228 Fix CI
  packages/extension/cypress/e2e/networks.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/cypress/e2e/wallet_management.cy.ts
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Labels: E2E

#230 Change about description
  packages/extension/src/components/pages/About/About.tsx
Labels: enhancement

#225 Fix useFees hook
  packages/extension/src/hooks/useFees/useFees.test.ts
  packages/extension/src/hooks/useFees/useFees.ts
Labels: bugfix

#233 Release 3.4.1
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#234 Receive Payment via QR code & Devnet Fund Wallet Functionality
  packages/extension/package.json
  packages/extension/src/App.tsx
  packages/extension/src/components/organisms/Header/Header.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/pages/ReceivePayment/ReceivePayment.tsx
  packages/extension/src/components/pages/ReceivePayment/index.ts
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/routes.ts
  yarn.lock
Labels: enhancement

#235 Modify ReceivePayment UI
  packages/extension/cypress/e2e/receive.cy.ts
  packages/extension/src/components/pages/ReceivePayment/ReceivePayment.tsx
Labels: enhancement

#226 Offline notification
  packages/extension/cypress/e2e/wallet_management.cy.ts
  packages/extension/src/components/atoms/OfflineBanner/OfflineBanner.tsx
  packages/extension/src/components/atoms/OfflineBanner/index.ts
  packages/extension/src/components/atoms/OfflineBanner/style.css
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.test.tsx
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx
  packages/extension/src/components/molecules/TextCopy/TextCopy.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.test.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/pages/About/About.tsx
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewWallet/ConfirmPassword/ConfirmPassword.tsx
  packages/extension/src/components/pages/AddNewWallet/CreateNewWallet/CreateNewWallet.test.tsx
  packages/extension/src/components/pages/AddNewWallet/ImportNewWallet/ImportNewWallet.tsx
  packages/extension/src/components/pages/AddNewWallet/ImportNewWallet/ImportSeed/ImportSeed.test.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/CreatePassword/CreatePassword.test.tsx
  packages/extension/src/components/pages/CreateWallet/ConfirmSeed/ConfirmSeed.test.tsx
  packages/extension/src/components/pages/CreateWallet/CreateWallet.test.tsx
  packages/extension/src/components/pages/CreateWallet/SecretSeed/SecretSeed.test.tsx
  packages/extension/src/components/pages/CreateWallet/SecretSeed/SecretSeed.tsx
  packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.test.tsx
  packages/extension/src/components/pages/ImportSecretNumbers/SecretNumbers/SecretNumbers.tsx
  packages/extension/src/components/pages/ImportWallet/ImportWallet.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/components/templates/AsyncTransaction/AsyncTransaction.tsx
  packages/extension/src/components/templates/ErrorBoundary/ErrorBoundary.tsx
  packages/extension/src/components/templates/PageWithHeader/PageWithHeader.tsx
  packages/extension/src/components/templates/PageWithNavMenu/PageWithNavMenu.tsx
  packages/extension/src/components/templates/PageWithReturn/PageWithReturn.tsx
  packages/extension/src/components/templates/PageWithStepper/PageWithStepper.tsx
  packages/extension/src/components/templates/PageWithTitle/PageWithTitle.tsx
  packages/extension/src/constants/links.ts
  packages/extension/src/constants/sizes.ts
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Labels: enhancement

#236 Add 'Could not establish connection.' to the list of recognized conne…
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Labels: dependencies

#238 Release 3.4.2
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#239 Refactor routes & helpers
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background/utils/focusOrCreatePopupWindow.ts
  packages/extension/src/components/pages/ListWallets/Wallet/Wallet.tsx
  packages/extension/src/components/pages/routes/app-routes.tsx
  packages/extension/src/components/pages/routes/index.ts
  packages/extension/src/components/pages/routes/private.routes.ts
  packages/extension/src/components/pages/routes/public.routes.ts
  packages/extension/src/constants/index.ts
  packages/extension/src/constants/navigation.tsx
  packages/extension/src/constants/paths.ts
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/inject-path-params.helpers.test.ts
  packages/extension/src/utils/inject-path-params.helpers.ts
  packages/extension/src/utils/typeof-fns.test.ts
  packages/extension/src/utils/typeof-fns.ts
Labels: refactor

#241 Handle not activated account during an API transaction
  packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/hooks/useFees/useFees.ts
  packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
Labels: enhancement

#143 Display NFTs
  packages/constants/src/payload/payload.types.ts
  packages/constants/src/xrpl/nft.constant.ts
  packages/constants/src/xrpl/nft.types.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/cypress/e2e/wallet_management.cy.ts
  packages/extension/package.json
  packages/extension/src/components/atoms/NFTImage/NFTImage.tsx
  packages/extension/src/components/atoms/NFTImage/index.ts
  packages/extension/src/components/atoms/Tokens/GemWallet/GemWallet.tsx
  packages/extension/src/components/atoms/TruncatedText/TruncatedText.tsx
  packages/extension/src/components/atoms/TruncatedText/index.ts
  packages/extension/src/components/atoms/index.ts
  packages/extension/src/components/molecules/NFTCard/NFTCard.test.tsx
  packages/extension/src/components/molecules/NFTCard/NFTCard.tsx
  packages/extension/src/components/molecules/NFTCard/index.ts
  packages/extension/src/components/molecules/NetworkIndicator/AddCustomNetworkDialog.tsx
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx
  packages/extension/src/components/molecules/index.ts
  packages/extension/src/components/organisms/NFTDetails/NFTDetails.tsx
  packages/extension/src/components/organisms/NFTDetails/index.ts
  packages/extension/src/components/organisms/NFTListing/NFTListing.tsx
  packages/extension/src/components/organisms/NFTListing/index.ts
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/organisms/index.ts
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm.tsx
  packages/extension/src/components/pages/NFTViewer/NFTViewer.tsx
  packages/extension/src/components/pages/NFTViewer/index.ts
  packages/extension/src/components/pages/index.ts
  packages/extension/src/components/pages/routes/private.routes.ts
  packages/extension/src/constants/navigation.tsx
  packages/extension/src/constants/paths.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/NFTDataResolver.test.ts
  packages/extension/src/utils/NFTDataResolver.ts
  packages/extension/src/utils/NFTViewer.test.ts
  packages/extension/src/utils/NFTViewer.ts
  packages/extension/src/utils/image.test.ts
  packages/extension/src/utils/image.ts
  packages/extension/src/utils/index.ts
  yarn.lock
Labels: enhancement

#242 Release 3.4.3
  packages/constants/package.json
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#245 Fix error with too many decimal during sending XRP
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
Labels: bugfix

#247 Collab 1
  packages/extension/public/collabs/XPUNKS/XPUNKS-Logo-Full-White.png
  packages/extension/src/components/misc/collabs/XPUNKS_1/XPUNKS_1.tsx
  packages/extension/src/components/misc/collabs/XPUNKS_1/index.ts
  packages/extension/src/components/misc/collabs/index.ts
  packages/extension/src/components/misc/index.ts
  packages/extension/src/components/organisms/Header/Header.tsx
  packages/extension/src/constants/storage.ts
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/storageChromeSession.ts
Labels: enhancement

#249 Handle domain field method in NFT data resolver
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/utils/NFTDataResolver.ts
Labels: enhancement

#250 Release 3.4.5
  packages/extension/package.json
  packages/extension/public/manifest.json
Labels: dependencies

#251 Fix 'Port closed' issue
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/content/index.ts
Labels: bugfix

#252 Ensure minimumFractionDigits range in formatValue function
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
Labels: bugfix

#254 Resolve NFT image when the URI is an ipfs to a direct image link
  packages/extension/src/utils/NFTDataResolver.test.ts
  packages/extension/src/utils/NFTDataResolver.ts
Labels: bugfix

#255 Add Account deletion process
  packages/extension/cypress/e2e/delete_account.cy.ts
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/DeleteAccount/DeleteAccount.tsx
  packages/extension/src/components/pages/DeleteAccount/DeleteAccountConfirm.tsx
  packages/extension/src/components/pages/DeleteAccount/DeleteAccountForm.tsx
  packages/extension/src/components/pages/DeleteAccount/index.ts
  packages/extension/src/components/pages/EnterPasswordDanger/EnterPasswordDanger.tsx
  packages/extension/src/components/pages/EnterPasswordDanger/index.ts
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/Settings/Settings.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/components/pages/routes/private.routes.ts
  packages/extension/src/constants/paths.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/errors.ts
Labels: enhancement
