Repository GemWallet/gemwallet-extension, pull requests merged in 2023-09, with the labels that each got.

#219 Submit transactions in bulk
  .vscode/settings.json
  packages/api/src/index.ts
  packages/api/src/submitBulkTransactions/index.ts
  packages/api/src/submitBulkTransactions/submitBulkTransactions.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/network/network.constant.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/submit_transactions_bulk.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/content/index.ts
  packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx
  packages/extension/src/components/organisms/DisplayXRPLTransaction/DisplayXRPLTransaction.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/Permissions/Permissions.tsx
  packages/extension/src/components/pages/Permissions/index.ts
  packages/extension/src/components/pages/Settings/Settings.tsx
  packages/extension/src/components/pages/SignTransaction/SignTransaction.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/PermissionRequiredView/PermissionRequiredView.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/PermissionRequiredView/index.ts
  packages/extension/src/components/pages/SubmitBulkTransactions/RecapView/RecapView.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/RecapView/index.ts
  packages/extension/src/components/pages/SubmitBulkTransactions/StepperView/StepperView.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/StepperView/index.ts
  packages/extension/src/components/pages/SubmitBulkTransactions/SubmitBulkTransactions.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/index.ts
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/components/pages/routes/private.routes.ts
  packages/extension/src/components/templates/AsyncTransaction/AsyncTransaction.tsx
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/paths.ts
  packages/extension/src/constants/storage.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/contexts/LedgerContext/utils/connectToLedger.ts
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
  packages/extension/src/hooks/useFees/useFees.ts
  packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/login.test.ts
  packages/extension/src/utils/login.ts
  packages/extension/src/utils/parseFromString.test.ts
  packages/extension/src/utils/parseFromString.ts
  packages/extension/src/utils/storage.ts
  packages/extension/src/utils/storageChrome.ts
  packages/extension/src/utils/storageChromeLocal.ts
  packages/extension/src/utils/storageChromeSession.ts
  packages/extension/src/utils/storageLocal.ts
Labels: enhancement

#256 Fix messaging for consecutive transactions
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/background/utils/focusOrCreatePopupWindow.ts
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/ShareNFT/ShareNFT.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/components/pages/Welcome/Welcome.test.tsx
  packages/extension/src/constants/storage.ts
  packages/extension/src/contexts/TransactionProgressContext/TransactionProgressContext.tsx
  packages/extension/src/contexts/TransactionProgressContext/index.ts
  packages/extension/src/contexts/index.ts
  packages/extension/src/index.tsx
Labels: bugfix

#263 Bump packages for the release 3.5.0
  packages/api/package.json
  packages/constants/package.json
  packages/extension/package.json
  packages/extension/public/manifest.json
  packages/extension/src/components/organisms/DisplayXRPLTransaction/DisplayXRPLTransaction.tsx
  yarn.lock
Labels: dependencies

#268 Fix popups handling in messaging system
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/components/pages/SignTransaction/SignTransaction.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/SubmitBulkTransactions.tsx
Labels: bugfix

#269 Improve UX for password fields
  packages/extension/src/components/pages/CreatePassword/CreatePassword.test.tsx
  packages/extension/src/components/pages/CreatePassword/CreatePassword.tsx
  packages/extension/src/components/pages/Login/Login.test.tsx
  packages/extension/src/components/pages/Login/Login.tsx
Labels: enhancement

#271 Fix reject messages on popup close
  packages/api/src/submitBulkTransactions/submitBulkTransactions.ts
  packages/api/templates/index.html
  packages/api/templates/indexv2.html
  packages/constants/src/errors/errors.constant.ts
  packages/constants/src/index.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/background/utils/focusOrCreatePopupWindow.ts
  packages/extension/src/chromeServices/background/utils/rejectOnClose.ts
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/pages/SignTransaction/SignTransaction.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/SubmitBulkTransactions.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/constants/apiErrors.ts
  packages/extension/src/constants/storage.ts
Labels: bugfix

#272 Handle API calls in offline mode
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.test.tsx
  packages/extension/src/components/pages/AddNewWallet/ConfirmPassword/ConfirmPassword.tsx
  packages/extension/src/components/pages/AddNewWallet/CreateNewWallet/CreateNewWallet.test.tsx
  packages/extension/src/components/pages/AddNewWallet/ImportNewWallet/ImportSeed/ImportSeed.test.tsx
  packages/extension/src/components/pages/CreatePassword/CreatePassword.test.tsx
  packages/extension/src/components/pages/CreateWallet/ConfirmSeed/ConfirmSeed.test.tsx
  packages/extension/src/components/pages/CreateWallet/CreateWallet.test.tsx
  packages/extension/src/components/pages/CreateWallet/SecretSeed/SecretSeed.test.tsx
  packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.test.tsx
  packages/extension/src/components/pages/ImportSecretNumbers/SecretNumbers/SecretNumbers.tsx
  packages/extension/src/components/pages/SignTransaction/SignTransaction.tsx
  packages/extension/src/components/pages/routes/hideOfflineBanner.routes.ts
  packages/extension/src/components/pages/routes/index.ts
  packages/extension/src/components/templates/AsyncTransaction/AsyncTransaction.tsx
  packages/extension/src/components/templates/ErrorBoundary/ErrorBoundary.tsx
  packages/extension/src/components/templates/PageWithHeader/PageWithHeader.tsx
  packages/extension/src/components/templates/PageWithNavMenu/PageWithNavMenu.tsx
  packages/extension/src/components/templates/PageWithReturn/PageWithReturn.tsx
  packages/extension/src/components/templates/PageWithStepper/PageWithStepper.tsx
  packages/extension/src/components/templates/PageWithTitle/PageWithTitle.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
  packages/extension/src/contexts/ServerContext/ServerContext.tsx
  packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
Labels: bugfix

#273 Bump packages to 3.5.1
  packages/api/package.json
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#274 Remove extension build
  .gitignore
  dist/gemwallet-api.js
Labels: dependencies

#267 Export TransactionBulkResponse type to the API
  packages/api/src/index.ts
Labels: bugfix

#280 Upgrade cypress to 12.17
  packages/extension/package.json
  yarn.lock
Labels: dependencies

#275 Disable login after too many wrong password attempts
  packages/extension/src/components/pages/Login/Login.tsx
Labels: enhancement

#282 Improve settings view
  packages/constants/src/message/message.types.ts
  packages/extension/src/components/pages/Settings/MenuGroup.tsx
  packages/extension/src/components/pages/Settings/Settings.tsx
Labels: enhancement

#284 Add layouts in NFT Viewer
  packages/extension/src/components/atoms/NFTImage/NFTImage.tsx
  packages/extension/src/components/molecules/NFTCard/NFTCard.tsx
  packages/extension/src/components/organisms/NFTListing/NFTListing.tsx
  packages/extension/src/components/pages/NFTViewer/NFTViewer.tsx
  packages/extension/src/components/templates/PageWithHeader/PageWithHeader.tsx
Labels: enhancement

#283 Add token search bar
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm/StepConfirm.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm/index.ts
  packages/extension/src/components/pages/AddNewTrustline/StepForm/SearchToken/SearchToken.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepForm/SearchToken/index.ts
  packages/extension/src/components/pages/AddNewTrustline/StepForm/StepForm.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepForm/index.ts
  packages/extension/src/components/pages/AddNewTrustline/StepWarning/StepWarning.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepWarning/index.ts
  packages/extension/src/components/pages/AddNewTrustline/TokenModal.tsx
  packages/extension/src/components/pages/AddNewTrustline/index.ts
  packages/extension/src/components/pages/Settings/Settings.tsx
  packages/extension/src/constants/index.ts
  packages/extension/src/constants/xrplmeta.ts
  packages/extension/src/types/index.ts
  packages/extension/src/types/xrplMeta.types.ts
Labels: enhancement

#288 Fix close button in Token search Modal
  packages/extension/src/components/pages/AddNewTrustline/TokenModal.tsx
Labels: bugfix

#266 Add token icons for token listing
  packages/extension/src/components/molecules/TokenDisplay/TokenDisplay.tsx
  packages/extension/src/components/molecules/TokenDisplay/TokenInfo/RenderTokenIcon/RenderTokenIcon.test.tsx
  packages/extension/src/components/molecules/TokenDisplay/TokenInfo/RenderTokenIcon/RenderTokenIcon.tsx
  packages/extension/src/components/molecules/TokenDisplay/TokenInfo/RenderTokenIcon/index.ts
  packages/extension/src/components/molecules/TokenDisplay/TokenInfo/TokenInfo.tsx
  packages/extension/src/components/molecules/TokenDisplay/TokenInfo/index.ts
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
Labels: enhancement

#292 Fix NFT viewer scrolling
  packages/extension/src/components/organisms/NFTListing/NFTListing.tsx
Labels: bugfix

#265 Improve NavBar styling
  packages/extension/src/components/organisms/NFTListing/NFTListing.tsx
  packages/extension/src/components/organisms/NavMenu/NavMenu.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/pages/NFTViewer/NFTViewer.tsx
  packages/extension/src/components/templates/PageWithHeader/PageWithHeader.tsx
  packages/extension/src/components/templates/PageWithNavMenu/PageWithNavMenu.tsx
  packages/extension/src/constants/colors.ts
  packages/extension/src/contexts/NavBarContext/NavBarContext.tsx
  packages/extension/src/contexts/NavBarContext/index.ts
  packages/extension/src/contexts/index.ts
  packages/extension/src/index.tsx
Labels: enhancement

#293 Release 3.5.3
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#291 Refactor Dialog page
  packages/extension/src/components/molecules/NFTCard/NFTCard.tsx
  packages/extension/src/components/molecules/NetworkIndicator/AddCustomNetworkDialog.tsx
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx
  packages/extension/src/components/organisms/NFTDetails/NFTDetails.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/templates/DialogPage/DialogPage.tsx
  packages/extension/src/components/templates/DialogPage/index.ts
  packages/extension/src/components/templates/index.ts
Labels: refactor

#295 Improve NFT viewer UI
  packages/extension/src/components/molecules/NFTCard/NFTCard.tsx
  packages/extension/src/components/organisms/NFTDetails/NFTDetails.tsx
Labels: enhancement
