Repository GemWallet/gemwallet-extension, pull requests merged in 2023-07, with the labels that each got.

#160 Submit Transaction
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/index.ts
  packages/api/src/submitTransaction/index.ts
  packages/api/src/submitTransaction/submitTransaction.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/sign_transaction.cy.ts
  packages/extension/package.json
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx
  packages/extension/src/components/organisms/BaseTransaction/hooks/useFees.ts
  packages/extension/src/components/organisms/DisplayXRPLTransaction/DisplayXRPLTransaction.tsx
  packages/extension/src/components/organisms/DisplayXRPLTransaction/index.ts
  packages/extension/src/components/organisms/index.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/SubmitTransaction/index.ts
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
  packages/extension/src/utils/parseFromString.test.ts
  packages/extension/src/utils/parseFromString.ts
  yarn.lock
Labels: enhancement

#189 Fix the issue with too long wallet name
  packages/extension/src/components/organisms/Header/Header.tsx
  packages/extension/src/components/pages/EditWallet/EditWallet.tsx
  packages/extension/src/components/pages/ListWallets/Wallet/Wallet.tsx
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/truncateWalletName.test.ts
  packages/extension/src/utils/truncateWalletName.ts
Labels: bugfix

#191 Update sendPayment & setTrustline endpoints
  packages/constants/src/payload/payload.types.ts
  packages/extension/src/components/organisms/BaseTransaction/hooks/useTransactionStatus.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
Labels: enhancement

#196 Fix UI issues
  packages/api/src/helpers/extensionMessaging.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/components/organisms/BaseTransaction/hooks/useFees.ts
  packages/extension/src/components/organisms/TokenListing/TokenListing.test.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepWarning.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/constants/server.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/convertCurrencyString.test.ts
  packages/extension/src/utils/convertCurrencyString.ts
  packages/extension/src/utils/convertHexCurrencyString.test.ts
  packages/extension/src/utils/convertHexCurrencyString.ts
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
  packages/extension/src/utils/index.ts
Labels: bug

#200 Refactor/breakdown extension scripts
  packages/extension/craco.config.js
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/background/utils/focusOrCreatePopupWindow.test.ts
  packages/extension/src/chromeServices/background/utils/focusOrCreatePopupWindow.ts
  packages/extension/src/chromeServices/content/index.ts
Labels: enhancement

#199 Add custom networks
  packages/api/src/getNetwork/getNetwork.ts
  packages/constants/src/network/network.constant.ts
  packages/constants/src/network/network.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/cypress/e2e/networks.cy.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/components/molecules/NetworkIndicator/ActiveNetworkDeleteDialog/ActiveNetworkDeleteDialog.tsx
  packages/extension/src/components/molecules/NetworkIndicator/ActiveNetworkDeleteDialog/index.ts
  packages/extension/src/components/molecules/NetworkIndicator/AddCustomNetworkDialog.tsx
  packages/extension/src/components/molecules/NetworkIndicator/DeleteNetworkDialog/DeleteNetworkDialog.tsx
  packages/extension/src/components/molecules/NetworkIndicator/DeleteNetworkDialog/index.ts
  packages/extension/src/components/molecules/NetworkIndicator/NetworkDisplay/NetworkDisplay.tsx
  packages/extension/src/components/molecules/NetworkIndicator/NetworkDisplay/index.ts
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/constants/localStorage.ts
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
  packages/extension/src/hooks/index.ts
  packages/extension/src/hooks/useFees/index.ts
  packages/extension/src/hooks/useFees/useFees.ts
  packages/extension/src/hooks/useTransactionStatus/index.ts
  packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
  packages/extension/src/utils/network.test.ts
  packages/extension/src/utils/network.ts
Labels: enhancement

#204 Change login page
  packages/extension/cypress/e2e/wallet_management.cy.ts
  packages/extension/src/components/pages/Login/Login.test.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/Welcome/Welcome.test.tsx
  packages/extension/src/components/pages/Welcome/Welcome.tsx
Labels: enhancement

#206 Bump xrpl dependency to 2.9.1 & Refactor CI
  .github/workflows/integration.yml
  packages/constants/package.json
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/cypress/e2e/networks.cy.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/package.json
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  yarn.lock
Labels: dependencies

#207 Fix network connection handling
  packages/extension/src/components/molecules/NetworkIndicator/ErrorSwitchNetworkDialog/ErrorSwitchNetworkDialog.tsx
  packages/extension/src/components/molecules/NetworkIndicator/ErrorSwitchNetworkDialog/index.ts
  packages/extension/src/components/molecules/NetworkIndicator/NetworkIndicator.tsx
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Labels: bug

#210 Animated logo
  packages/extension/src/components/atoms/Logo/Logo.tsx
  packages/extension/src/components/pages/Login/Login.tsx
Labels: enhancement

#211 Feat/sentry session
  packages/extension/package.json
  packages/extension/src/index.tsx
  yarn.lock
Labels: dependencies

#203 Persist sessions
  packages/constants/src/index.ts
  packages/constants/src/message/message.constant.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/craco.config.js
  packages/extension/package.json
  packages/extension/public/manifest.json
  packages/extension/public/offscreen.html
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/background/utils/offscreen.ts
  packages/extension/src/chromeServices/background/utils/session.ts
  packages/extension/src/chromeServices/offscreen/index.ts
  packages/extension/src/components/pages/CreatePassword/CreatePassword.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/Welcome/Welcome.test.tsx
  packages/extension/src/contexts/BrowserContext/BrowserContext.tsx
  packages/extension/src/contexts/WalletContext/WalletContext.tsx
  yarn.lock
Labels: enhancement

#214 Add custom message if network is not connected within the tx history
  packages/extension/src/components/pages/History/History.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
Labels: enhancement

#215 Fix not enough funds on prepare payment
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
Labels: bugfix

#216 Change text for no tokens not connected
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/src/components/organisms/TokenListing/TokenListing.test.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
Labels: refactor

#217 Fix edge case when link could be undefined
  packages/extension/src/components/pages/ImportWallet/ImportWallet.tsx
Labels: bugfix

#193 Add events
  packages/api/src/index.ts
  packages/api/src/on/index.ts
  packages/api/src/on/on.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/network/network.constant.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/cypress/e2e/networks.cy.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/cypress/e2e/wallet_management.cy.ts
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/background/utils/session.ts
  packages/extension/src/chromeServices/content/index.ts
  packages/extension/src/components/pages/ListWallets/ListWallets.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Labels: enhancement

#220 Remove errors with events on dev env
  packages/extension/src/components/pages/ListWallets/ListWallets.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
Labels: bugfix
