Repository GemWallet/gemwallet-extension, pull requests merged in 2023-02, with the labels that each got.

#87 refactor document.getElementById to useRef
  packages/extension/src/components/pages/AddNewWallet/ConfirmPassword/ConfirmPassword.tsx
  packages/extension/src/components/pages/AddNewWallet/ImportNewWallet/ImportMnemonic/ImportMnemonic.tsx
  packages/extension/src/components/pages/AddNewWallet/ImportNewWallet/ImportSeed/ImportSeed.tsx
  packages/extension/src/components/pages/CreatePassword/CreatePassword.tsx
  packages/extension/src/components/pages/CreateWallet/ConfirmSeed/ConfirmSeed.tsx
  packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.tsx
  packages/extension/src/components/pages/Login/Login.tsx
Labels: dependencies

#89 Remove the NFTDevNet and add the AMMDevNet
  packages/constants/src/network/network.constant.ts
  packages/extension/cypress/e2e/networks.cy.ts
Labels: enhancement

#90 Fix issues with cypress
  packages/extension/cypress/e2e/wallet_management.cy.ts
Labels: E2E

#91 Fix/Selected Wallet
  packages/extension/src/contexts/WalletContext/WalletContext.tsx
Labels: bugfix

#92 Default network to Mainnet if loaded network is not supported
  packages/extension/src/utils/network.ts
Labels: bugfix

#94 Add transaction with other tokens
  packages/api/templates/index.html
  packages/constants/src/payload/payload.types.ts
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
Labels: dependencies

#95 Make the CDN compatible with unpkg
  dist/gemwallet-api.js
  packages/api/package.json
  packages/api/releaseNpm.js
Labels: enhancement

#96 Add e2e testing for the payment
  packages/extension/cypress/e2e/networks.cy.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/package.json
  packages/extension/src/components/templates/AsyncTransaction/AsyncTransaction.tsx
  packages/extension/src/components/templates/PageWithTitle/PageWithTitle.tsx
  yarn.lock
Labels: dependencies, E2E

#97 Add e2e testing for the trustlines
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
Labels: E2E

#98 Fix the loading of the selected wallet
  packages/extension/src/contexts/WalletContext/WalletContext.tsx
Labels: bugfix

#99 Release/2.3.0
  packages/api/package.json
  packages/extension/package.json
  yarn.lock
Labels: dependencies

#100 Add Transaction history
  packages/extension/package.json
  packages/extension/src/App.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.mock.ts
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.test.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/organisms/TransactionListing/index.ts
  packages/extension/src/components/organisms/index.ts
  packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.tsx
  packages/extension/src/components/pages/History/History.tsx
  packages/extension/src/components/pages/History/index.ts
  packages/extension/src/components/pages/index.ts
  packages/extension/src/components/templates/PageWithSpinner/PageWithSpinner.tsx
  packages/extension/src/constants/navigation.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/types/transaction.types.ts
  yarn.lock
Labels: enhancement

#101 Improve the estimation of transaction fees for trustlines
  package.json
  packages/extension/cypress/e2e/wallet_management.cy.ts
  packages/extension/package.json
  packages/extension/src/components/pages/Transaction/Transaction.tsx
Labels: bugfix

#102 Decode hex tokens
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/utils/convertCurrencyString.test.ts
  packages/extension/src/utils/convertCurrencyString.ts
  packages/extension/src/utils/index.ts
Labels: bugfix

#106 Add list NFT
  dist/gemwallet-api.js
  packages/api/jest.config.js
  packages/api/src/getNFT/getNFT.test.ts
  packages/api/src/getNFT/getNFT.ts
  packages/api/src/getNFT/index.ts
  packages/api/src/index.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/index.ts
  packages/constants/src/message/message.constant.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/constants/src/xrpl/nft.types.ts
  packages/extension/package.json
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/ShareAddress/ShareAddress.tsx
  packages/extension/src/components/pages/ShareNFT/ShareNFT.tsx
  packages/extension/src/components/pages/ShareNFT/index.ts
  packages/extension/src/components/pages/SharePublicKey/SharePublicKey.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/trustedApps.ts
  yarn.lock
Labels: dependencies

#107 Fix UI glitch when show seed
  packages/extension/src/components/pages/EditWallet/ShowSecret/ShowSecret.tsx
Labels: bugfix

#108 Fix Cypress tests after resolving UI
  packages/extension/cypress/e2e/wallet_management.cy.ts
Labels: bugfix

#109 Release 2.5.0
  packages/api/package.json
  packages/extension/package.json
  packages/extension/public/manifest.json
Labels: dependencies

#110 Refactor background service
  packages/extension/src/chromeServices/background.ts
Labels: enhancement
