Repository GemWallet/gemwallet-extension, pull requests merged in 2023-10, with the labels that each got.

#297 Add infos about destination tag in the Send Payment view
  packages/extension/src/components/pages/SendPayment/PreparePayment/DestinationTagInfoModal/DestinationTagInfoModal.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/DestinationTagInfoModal/index.ts
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
Labels: enhancement

#300 Regroup transactions by date in Transaction history view
  packages/extension/src/components/organisms/TransactionListing/TransactionDetails.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.test.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/organisms/TransactionListing/format.util.ts
Labels: enhancement

#299 Revamp Sign Message view
  packages/extension/src/components/molecules/ActionButtons/ActionButtons.tsx
  packages/extension/src/components/molecules/ActionButtons/index.ts
  packages/extension/src/components/molecules/DataCard/DataCard.tsx
  packages/extension/src/components/molecules/DataCard/index.ts
  packages/extension/src/components/molecules/index.ts
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
Labels: enhancement

#301 Fix decimal precision on the add trustline view
  packages/extension/src/components/pages/AddNewTrustline/StepForm/StepForm.tsx
Labels: bugfix

#302 Revamp Submit Transaction view
  packages/extension/cypress/e2e/sign_transaction.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/src/components/atoms/TransactionTextDescription/TransactionTextDescription.tsx
  packages/extension/src/components/atoms/TransactionTextDescription/index.ts
  packages/extension/src/components/atoms/index.ts
  packages/extension/src/components/molecules/ActionButtons/ActionButtons.tsx
  packages/extension/src/components/molecules/DataCard/DataCard.tsx
  packages/extension/src/components/molecules/InsufficientFundsWarning/InsufficientFundsWarning.tsx
  packages/extension/src/components/molecules/InsufficientFundsWarning/index.ts
  packages/extension/src/components/molecules/RawTransaction/RawTransaction.tsx
  packages/extension/src/components/molecules/RawTransaction/index.ts
  packages/extension/src/components/molecules/TransactionHeader/TransactionHeader.tsx
  packages/extension/src/components/molecules/TransactionHeader/index.ts
  packages/extension/src/components/molecules/index.ts
  packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx
  packages/extension/src/components/organisms/DisplayXRPLTransaction/DisplayXRPLTransaction.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
Labels: enhancement

#303 Create Transaction Page Template
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/templates/TransactionPage/TransactionPage.tsx
  packages/extension/src/components/templates/TransactionPage/index.ts
  packages/extension/src/components/templates/index.ts
Labels: refactor

#307 Revamp Sign Transaction view
  packages/extension/cypress/e2e/sign_transaction.cy.ts
  packages/extension/src/components/organisms/TransactionDetails/TransactionDetails.tsx
  packages/extension/src/components/pages/SignTransaction/SignTransaction.tsx
Labels: enhancement, refactor

#261 Handle server rotation on connection failure
  .vscode/settings.json
  packages/constants/src/network/network.constant.ts
  packages/extension/src/contexts/BrowserContext/BrowserContext.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
  packages/extension/src/utils/network.ts
Labels: bugfix

#308 Refactor AcceptNFTOffer view
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx
  packages/extension/src/components/organisms/TransactionDetails/TransactionDetails.tsx
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/contexts/LedgerContext/index.ts
  packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.test.ts
  packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.ts
  packages/extension/src/contexts/LedgerContext/utils/index.ts
  packages/extension/src/hooks/useFees/useFees.ts
  packages/extension/src/utils/baseParams.test.ts
  packages/extension/src/utils/baseParams.ts
Labels: enhancement, refactor

#309 Revamp NFT Transaction views
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.test.ts
  packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.ts
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
Labels: enhancement, refactor

#311 Hide account field in Transaction view
  packages/extension/cypress/e2e/sign_transaction.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx
Labels: enhancement

#313 Revamp Share views
  packages/extension/src/components/templates/SharingPage/SharingPage.tsx
Labels: enhancement, refactor

#312 Revamp other transaction views
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/cypress/e2e/sign_transaction.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm/StepConfirm.tsx
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/SendPayment/SendPayment.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.test.ts
  packages/extension/src/contexts/LedgerContext/utils/buildXRPLTransaction.ts
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
Labels: enhancement, refactor

#316 Improve transaction fields display
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx
Labels: enhancement

#315 Release 3.5.4
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#319 Fix popup size
  packages/extension/src/chromeServices/background/utils/focusOrCreatePopupWindow.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/constants/sizes.ts
  packages/extension/src/index.tsx
Labels: bugfix

#320 Release 3.5.5
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#324 Feat/citrouille
  packages/extension/package.json
  packages/extension/src/components/atoms/Logo/Logo.tsx
  packages/extension/src/components/organisms/Header/Header.tsx
  packages/extension/src/components/organisms/NavMenu/NavMenu.tsx
  packages/extension/src/components/pages/Welcome/Welcome.tsx
  packages/extension/src/constants/colors.ts
  packages/extension/src/constants/storage.ts
  packages/extension/src/contexts/NavBarContext/NavBarContext.tsx
  packages/extension/src/hooks/index.ts
  packages/extension/src/hooks/useFeatureFlags/index.ts
  packages/extension/src/hooks/useFeatureFlags/useFeatureFlags.ts
  packages/extension/src/index.tsx
  yarn.lock
Labels: enhancement

#321 Revamp Bulk Transactions view
  packages/extension/cypress/e2e/submit_transactions_bulk.cy.ts
  packages/extension/src/components/atoms/KeyValueDisplay/KeyValueDisplay.tsx
  packages/extension/src/components/atoms/KeyValueDisplay/index.ts
  packages/extension/src/components/atoms/TransactionTextDescription/TransactionTextDescription.tsx
  packages/extension/src/components/atoms/index.ts
  packages/extension/src/components/molecules/ActionButtons/ActionButtons.tsx
  packages/extension/src/components/molecules/DataCard/DataCard.tsx
  packages/extension/src/components/molecules/RawTransaction/RawTransaction.tsx
  packages/extension/src/components/molecules/TransactionNFTDisplay/TransactionNFTDisplay.tsx
  packages/extension/src/components/molecules/TransactionNFTDisplay/index.ts
  packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx
  packages/extension/src/components/molecules/index.ts
  packages/extension/src/components/pages/SubmitBulkTransactions/ConfirmationDialog/ConfirmationDialog.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/ConfirmationDialog/index.ts
  packages/extension/src/components/pages/SubmitBulkTransactions/RecapView/RecapView.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/StepperView/StepperNavigation.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/StepperView/StepperView.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/StepperView/TransactionsDisplay.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/SubmitBulkTransactions.tsx
  packages/extension/src/components/templates/TransactionPage/TransactionPage.tsx
Labels: enhancement, refactor

#323 Refactor messaging system for XRPL protocol endpoints
  packages/api/src/helpers/extensionMessaging.ts
  packages/extension/cypress/e2e/sign_transaction.cy.ts
  packages/extension/cypress/e2e/submit_transaction.cy.ts
  packages/extension/cypress/e2e/submit_transactions_bulk.cy.ts
  packages/extension/cypress/utils/navigation.ts
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/components/pages/SignTransaction/SignTransaction.tsx
  packages/extension/src/components/pages/SubmitBulkTransactions/SubmitBulkTransactions.tsx
  packages/extension/src/components/pages/SubmitTransaction/SubmitTransaction.tsx
  packages/extension/src/constants/storage.ts
  packages/extension/src/hooks/index.ts
  packages/extension/src/hooks/useFetchFromSessionStorage/index.ts
  packages/extension/src/hooks/useFetchFromSessionStorage/useFetchFromSessionStorage.test.ts
  packages/extension/src/hooks/useFetchFromSessionStorage/useFetchFromSessionStorage.ts
  packages/extension/src/utils/baseParams.ts
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/parseParams.test.ts
  packages/extension/src/utils/parseParams.ts
Labels: refactor

#325 Refactor messaging system for NFT endpoints
  packages/api/src/helpers/extensionMessaging.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/cypress/utils/navigation.ts
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CreateNFTOffer/CreateNFTOffer.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/utils/baseParams.test.ts
  packages/extension/src/utils/baseParams.ts
  packages/extension/src/utils/parseParams.test.ts
  packages/extension/src/utils/parseParams.ts
Labels: refactor

#327 Refactor messaging system for DEX endpoints
  packages/api/src/helpers/extensionMessaging.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/components/molecules/XRPLTransaction/XRPLTransaction.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/utils/parseParams.test.ts
  packages/extension/src/utils/parseParams.ts
Labels: refactor

#328 Refactor messaging system for other endpoints
  packages/api/src/helpers/extensionMessaging.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/cypress/utils/navigation.ts
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/components/atoms/NumericInput/NumericInput.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepForm/StepForm.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/utils/parseParams.test.ts
  packages/extension/src/utils/parseParams.ts
  packages/extension/src/utils/storageChromeSession.ts
Labels: refactor
