Repository GemWallet/gemwallet-extension, pull requests merged in 2023-06, with the labels that each got.

#158 feat(testnet) : add button for get funds on faucet
  packages/extension/src/components/organisms/TokenListing/TokenListing.test.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
Labels: enhancement

#157 Rework API errors
  packages/api/src/getAddress/getAddress.test.ts
  packages/api/src/getAddress/getAddress.ts
  packages/api/src/getNFT/getNFT.test.ts
  packages/api/src/getNFT/getNFT.ts
  packages/api/src/getNetwork/getNetwork.test.ts
  packages/api/src/getNetwork/getNetwork.ts
  packages/api/src/getPublicKey/getPublicKey.test.ts
  packages/api/src/getPublicKey/getPublicKey.ts
  packages/api/src/helpers/errors.test.ts
  packages/api/src/helpers/errors.ts
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/sendPayment/sendPayment.test.ts
  packages/api/src/sendPayment/sendPayment.ts
  packages/api/src/setTrustline/setTrustline.ts
  packages/api/src/signMessage/signMessage.ts
  packages/api/templates/index.html
  packages/constants/package.json
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/ShareAddress/ShareAddress.tsx
  packages/extension/src/components/pages/ShareNFT/ShareNFT.tsx
  packages/extension/src/components/pages/SharePublicKey/SharePublicKey.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/utils/errors.test.ts
  packages/extension/src/utils/errors.ts
Labels: enhancement

#161 Rename const parameters
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/constants/parameters.ts
Labels: refactor

#163 Feat/errors UI
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/SignMessage/SignMessage.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/constants/apiErrors.ts
  packages/extension/src/constants/index.ts
Labels: enhancement

#164 Export all the types used for the V3
  packages/api/src/index.ts
Labels: enhancement

#165 Stop video recording on cypress CI
  .github/workflows/integration.yml
  packages/extension/cypress.config.ts
Labels: enhancement

#166 Add new trustline from the UI
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/components/organisms/TokenListing/TokenListing.test.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepForm.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepWarning.tsx
  packages/extension/src/components/pages/AddNewTrustline/index.ts
  packages/extension/src/constants/sizes.ts
  packages/extension/src/utils/hexConverter.test.ts
  packages/extension/src/utils/hexConverter.ts
  packages/extension/src/utils/index.ts
Labels: enhancement

#172 Feat/upgrade webpack cli
  package.json
  packages/api/package.json
  packages/api/webpack.dev.js
  packages/api/webpack.prod.js
  packages/extension/src/utils/crypto.test.ts
  yarn.lock
Labels: dependencies

#175 Feat/add trustline form checks
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/src/components/pages/AddNewTrustline/StepForm.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
Labels: enhancement

#151 Update trustline from the UI
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/components/atoms/NumericInput/NumericInput.tsx
  packages/extension/src/components/molecules/TokenDisplay/TokenDisplay.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.test.tsx
  packages/extension/src/components/organisms/TokenListing/TokenListing.tsx
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepConfirm.tsx
  packages/extension/src/components/pages/AddNewTrustline/StepForm.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
Labels: enhancement

#177 Release 3.1.0
  packages/extension/package.json
  packages/extension/public/manifest.json
  yarn.lock
Labels: dependencies

#168 Mint NFT
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/index.ts
  packages/api/src/mintNFT/index.ts
  packages/api/src/mintNFT/mintNFT.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/constants/src/xrpl/basic.types.ts
  packages/extension/cypress/e2e/mintNFT.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx
  packages/extension/src/components/organisms/BaseTransaction/index.ts
  packages/extension/src/components/organisms/index.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/MintNFT/MintNFT.tsx
  packages/extension/src/components/pages/MintNFT/index.ts
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/components/templates/PageWithTitle/PageWithTitle.tsx
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/baseParams.test.ts
  packages/extension/src/utils/baseParams.ts
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
  packages/extension/src/utils/getLastItemFromArray.test.ts
  packages/extension/src/utils/getLastItemFromArray.ts
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/parseFromString.test.ts
  packages/extension/src/utils/parseFromString.ts
  packages/extension/src/utils/transaction.test.ts
  packages/extension/src/utils/transaction.ts
Labels: enhancement

#171 Cancel NFT offer
  packages/api/src/cancelNFTOffer/cancelNFTOffer.ts
  packages/api/src/cancelNFTOffer/index.ts
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/index.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/pages/CancelNFTOffer/CancelNFTOffer.tsx
  packages/extension/src/components/pages/CancelNFTOffer/index.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/parseFromString.test.ts
  packages/extension/src/utils/parseFromString.ts
Labels: enhancement

#173 Accept NFT offer
  packages/api/src/acceptNFTOffer/acceptNFTOffer.ts
  packages/api/src/acceptNFTOffer/index.ts
  packages/api/src/index.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/AcceptNFTOffer/AcceptNFTOffer.tsx
  packages/extension/src/components/pages/AcceptNFTOffer/index.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
Labels: enhancement

#174 Burn NFT
  packages/api/src/burnNFT/burnNFT.ts
  packages/api/src/burnNFT/index.ts
  packages/api/src/index.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/NFT.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/BurnNFT/BurnNFT.tsx
  packages/extension/src/components/pages/BurnNFT/index.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
Labels: enhancement

#176 Set Account
  packages/api/src/index.ts
  packages/api/src/setAccount/index.ts
  packages/api/src/setAccount/setAccount.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/constants/src/xrpl/basic.types.ts
  packages/extension/cypress/e2e/set_account.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/SetAccount/SetAccount.tsx
  packages/extension/src/components/pages/SetAccount/index.ts
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/format.ts
  packages/extension/src/utils/parseFromString.test.ts
  packages/extension/src/utils/parseFromString.ts
Labels: enhancement

#180 Create Offer
  packages/api/src/createOffer/createOffer.ts
  packages/api/src/createOffer/index.ts
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/index.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/constants/src/xrpl/basic.types.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/organisms/BaseTransaction/BaseTransaction.tsx
  packages/extension/src/components/pages/CreateOffer/CreateOffer.tsx
  packages/extension/src/components/pages/CreateOffer/index.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/format.ts
  packages/extension/src/utils/parseFromString.test.ts
  packages/extension/src/utils/parseFromString.ts
Labels: enhancement

#182 Cancel Offer
  packages/api/src/cancelOffer/cancelOffer.ts
  packages/api/src/cancelOffer/index.ts
  packages/api/src/index.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/offers.cy.ts
  packages/extension/src/App.tsx
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/pages/CancelOffer/CancelOffer.tsx
  packages/extension/src/components/pages/CancelOffer/index.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/index.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/routes.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
Labels: enhancement
