Repository GemWallet/gemwallet-extension, pull requests merged in 2023-05, with the labels that each got.

#152 Handle memos, destinationTag, fee & flags in sendPayment API
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/index.ts
  packages/api/templates/index.html
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/components/organisms/TransactionListing/TransactionListing.tsx
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/SendPayment/ConfirmPayment/ConfirmPayment.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/components/pages/SendPayment/SendPayment.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
  packages/extension/src/utils/payment.test.ts
  packages/extension/src/utils/payment.ts
Labels: enhancement

#119 Fixed marker issue in NFTs
  packages/api/src/getNFT/getNFT.test.ts
  packages/api/src/getNFT/getNFT.ts
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/ShareNFT/ShareNFT.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
Labels: enhancement, refactor

#154 Refactor setTrustline API & handle memos, flags, fee
  packages/api/src/addTrustline/index.ts
  packages/api/src/helpers/extensionMessaging.ts
  packages/api/src/index.ts
  packages/api/src/setTrustline/index.ts
  packages/api/src/setTrustline/setTrustline.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/index.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/constants/src/xrpl/basic.types.ts
  packages/extension/cypress/e2e/trustlines.cy.ts
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/AddNewTrustline/AddNewTrustline.tsx
  packages/extension/src/components/pages/ShareNFT/ShareNFT.tsx
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/mocks/ledgerContext.ts
  packages/extension/src/utils/format.test.ts
  packages/extension/src/utils/format.ts
  packages/extension/src/utils/index.ts
  packages/extension/src/utils/parseFromString.test.ts
  packages/extension/src/utils/parseFromString.ts
  packages/extension/src/utils/payment.test.ts
  packages/extension/src/utils/payment.ts
Labels: refactor

#155 Handle sendPayment retrocompatibility
  packages/api/src/sendPayment/sendPayment.ts
  packages/constants/src/event/event.types.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/extension/cypress/e2e/payments.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/src/chromeServices/background.ts
  packages/extension/src/chromeServices/content.ts
  packages/extension/src/components/pages/Transaction/Transaction.tsx
  packages/extension/src/utils/parseFromString.ts
Labels: enhancement
