Repository GemWallet/gemwallet-extension, pull requests merged in 2024-01, with the labels that each got.

#343 Detect wrong NetworkID in Transaction views
  packages/constants/src/network/network.constant.ts
  packages/extension/src/components/organisms/TransactionDetails/TransactionDetails.tsx
  packages/extension/src/components/organisms/TransactionDetails/WrongNetworkIDModal/WrongNetworkIDModal.tsx
  packages/extension/src/components/organisms/TransactionDetails/WrongNetworkIDModal/index.ts
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
  packages/extension/src/hooks/useFees/useFees.test.ts
  packages/extension/src/hooks/useFees/useFees.ts
  packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
Labels: enhancement

#345 Update vscode settings
  .vscode/settings.json
Labels: dependencies

#338 Add setHook endpoint
  packages/api/src/index.ts
  packages/api/src/setHook/index.ts
  packages/api/src/setHook/setHook.ts
  packages/api/templates/index.html
  packages/constants/src/event/event.types.ts
  packages/constants/src/index.ts
  packages/constants/src/message/message.types.ts
  packages/constants/src/payload/payload.types.ts
  packages/constants/src/xrpl/basic.types.ts
  packages/constants/src/xrpl/hooks.types.ts
  packages/extension/cypress/e2e/hooks.cy.ts
  packages/extension/src/chromeServices/background/index.ts
  packages/extension/src/chromeServices/background/utils/rejectOnClose.ts
  packages/extension/src/chromeServices/content/index.ts
  packages/extension/src/components/molecules/RawTransaction/RawTransaction.tsx
  packages/extension/src/components/molecules/TransactionDisplay/HooksDisplay.tsx
  packages/extension/src/components/molecules/TransactionDisplay/TransactionDisplay.tsx
  packages/extension/src/components/molecules/TransactionDisplay/index.ts
  packages/extension/src/components/molecules/XRPLTransaction/index.ts
  packages/extension/src/components/molecules/index.ts
  packages/extension/src/components/organisms/TransactionDetails/TransactionDetails.tsx
  packages/extension/src/components/pages/Login/Login.tsx
  packages/extension/src/components/pages/SetHook/SetHook.tsx
  packages/extension/src/components/pages/SetHook/index.ts
  packages/extension/src/components/pages/SubmitBulkTransactions/StepperView/TransactionsDisplay.tsx
  packages/extension/src/components/pages/routes/private.routes.ts
  packages/extension/src/constants/parameters.ts
  packages/extension/src/constants/paths.ts
  packages/extension/src/contexts/LedgerContext/LedgerContext.tsx
  packages/extension/src/contexts/LedgerContext/chains/XRPL.ts
  packages/extension/src/contexts/LedgerContext/chains/Xahau.ts
  packages/extension/src/contexts/LedgerContext/utils/buildXahauTransaction.test.ts
  packages/extension/src/contexts/LedgerContext/utils/buildXahauTransaction.ts
  packages/extension/src/contexts/LedgerContext/utils/index.ts
  packages/extension/src/hooks/useFees/useFees.ts
  packages/extension/src/hooks/useTransactionStatus/useTransactionStatus.tsx
  packages/extension/src/mocks/ledgerContext.ts
Labels: enhancement

#346 Display token infos in Send Payment view
  packages/extension/cypress/e2e/receive.cy.ts
  packages/extension/cypress/e2e/send_token.cy.ts
  packages/extension/src/components/molecules/TokenDisplay/TokenDisplay.tsx
  packages/extension/src/components/pages/SendPayment/PreparePayment/PreparePayment.tsx
  packages/extension/src/utils/fetchTokenData.ts
  packages/extension/src/utils/index.ts
Labels: enhancement

#349 Fix messaging for setHook endpoint
  packages/extension/src/chromeServices/background/index.ts
Labels: bugfix

#350 Add chain in getNetwork response
  packages/constants/src/payload/payload.types.ts
  packages/extension/src/App.tsx
Labels: enhancement

#351 Fix custom networks management
  packages/constants/src/network/network.constant.ts
  packages/extension/src/components/organisms/TransactionDetails/TransactionDetails.tsx
  packages/extension/src/contexts/NetworkContext/NetworkContext.tsx
  packages/extension/src/utils/network.ts
Labels: bugfix
